### ISSUE TITLE
Maximum call stack exceeded error

### ISSUE THREAD

**Issue by sarunaskas** [mprozil/PlayAxis#2]
Hello,

I seemed to be getting the maximum call stack exceeded error while compiling the visual.

As reported here https://github.com/Microsoft/PowerBI-visuals/issues/136 

The solution of moving the "node_modules/d3/d3.js" line to the externalJS property in the pbiviz.json file did the trick.

**Comment by mprozil** [comment]
Hi,

Thank you for reporting this issue. I have moved the file to the externalJS property as you suggested..
