### ISSUE TITLE
Allow delays between 0ms and 500ms

### ISSUE THREAD

**Issue by agroberman** [mprozil/PlayAxis#3]
Hi,

Thanks for making such a great visualization! I have a use for which I'd like each step to be much quicker, so as to give the illusion of real-time animation. Would it be possible to relax the minimum duration constraint from 500ms all the way down to 0ms or 1ms? I realize that the actual performance may not be optimal if the delay is shorter than what can be rendered, but I'd like to see just how quickly I can make my transitions go for this project.

Thanks again!

**Comment by mprozil** [comment]
Hi,
I just submitted an updated version (1ms minimum) to the office store. It normally takes some days until you can see the changes. I hope it's useful. Thanks.
