### ISSUE TITLE
Sorting in the visual

### ISSUE THREAD

**Issue by prateekraina** [mprozil/PlayAxis#4]
Hi,

Can you add a feature to sort the column in ASC or DESC in this visual. It will be really helpful in cases where lakhs of TimeStamp is present and you want to see the data going from latest to earliest.

Prateek Raina

**Comment by mprozil** [comment]
Hi Prateek, 

Just added the sort feature to PlayAxis. It will take a couple of days to be updated in the Office Store but you can test the dev version [here](http://github.com/mprozil/PlayAxis/tree/master/dist). 
Thank you so much for the suggestion. 

Margarida

**Comment by prateekraina** [comment]
Hi Margarida,

It works perfectly. Thank you so much for such prompt response.

Prateek Raina

**Comment by jocooler** [comment]
I still seem to have gotten the old version from the store - but the new one works great. Any chance of getting the store updated?

**Comment by mprozil** [comment]
@jocooler can you double check? I have updated the store version last month and the Sort feature is included - as you can see in the screenshot:
 
![print sort](https://user-images.githubusercontent.com/24993594/41930106-fae7602e-7971-11e8-9fe6-c8d1cbb94a0d.png)

**Comment by jocooler** [comment]
I think you're right - I think I clicked on the title not the sort icon.
And when I downloaded the version you have on GitHub I clicked the correct
one. My mistake. Thanks for a great visual!

**Comment by lottevandongen** [comment]
Hi, 
In my version of Power BI I do not see a sort button for the Play Axis scatterplot visual. Is there any other way to make sure the axis is sorted correctly? 
Best, Lotte

**Comment by iuriemaxim** [comment]
@lottevandongen most probably the field on which sorting is aplied shoud be a date or dateTime type.
